"""
app.py
-------
Main Flask application for the AI-Powered Registration Intelligence
& Attendee Management System (Infosys Springboard Virtual Internship
- Milestone 1).
"""

import os
import io
import csv
import re
import json
import time
import base64
from datetime import datetime

from flask import (
    Flask, render_template, request, redirect, url_for,
    session, jsonify, flash, send_file, Response
)
from werkzeug.security import check_password_hash

import database as db
import ai_model
import operations as ops
import sponsorship as spx
import incidents as inc
import alerts
import event_intelligence as ei
import risk_engine as risk_engine_mod
import agent_orchestrator as orch
import decision_support as dsupport
from config import get_config

# QR + PDF (optional heavy libs, imported lazily where used to keep boot fast)
try:
    import qrcode
except ImportError:
    qrcode = None

app = Flask(__name__)
app.config.from_object(get_config())
app.secret_key = app.config["SECRET_KEY"]

EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
PHONE_REGEX = re.compile(r"^[6-9]\d{9}$")

# Participant Category options — used by the registration form, validation,
# dashboard/analytics breakdowns and reports.
PARTICIPANT_CATEGORIES = [
    "Student", "Professional", "Speaker", "Volunteer", "Organizer",
    "Sponsor", "VIP Guest", "Media", "Exhibitor",
]


# =================================================================
# QR CODE / REGISTRATION ID HELPERS
# =================================================================
def generate_registration_id(user_id):
    """Generate a Registration ID like REG-2026-0001."""
    return f"REG-{datetime.now().year}-{int(user_id):04d}"


def build_qr_payload(user):
    """Build the JSON payload embedded inside a participant's QR code."""
    return json.dumps({
        "registration_id": user.get("registration_id"),
        "name": user.get("name"),
        "email": user.get("email"),
        "phone": user.get("phone"),
        "participant_category": user.get("participant_category"),
    })


def generate_qr_image_bytes(payload_text):
    """Generate a PNG QR code image (bytes) for the given text payload."""
    if not qrcode:
        return None
    img = qrcode.make(payload_text)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf


def find_user_by_scan_code(code):
    """
    Resolve a scanned/entered check-in code to a user row. Supports:
      - Full JSON QR payload (as generated by build_qr_payload)
      - A bare Registration ID (e.g. REG-2026-0001)
      - A numeric attendee ID or an email address (manual entry)
    """
    code = (code or "").strip()
    if not code:
        return None

    # JSON QR payload
    try:
        payload = json.loads(code)
        if isinstance(payload, dict) and payload.get("registration_id"):
            return db.query_one(
                "SELECT * FROM users WHERE registration_id = ?", (payload["registration_id"],)
            )
    except (ValueError, TypeError):
        pass

    # Bare Registration ID
    if code.upper().startswith("REG-"):
        return db.query_one("SELECT * FROM users WHERE registration_id = ?", (code,))

    # Manual entry: numeric ID or email
    return db.query_one("SELECT * FROM users WHERE id = ? OR email = ?", (code, code))


# =================================================================
# APP INITIALIZATION
# =================================================================
@app.before_request
def ensure_db():
    if not os.path.exists(db.DB_PATH):
        db.init_db(force=True)


@app.after_request
def apply_security_headers(response):
    """Baseline security headers — safe defaults that don't break existing
    functionality (no CSP nonce machinery, no breaking inline scripts)."""
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    response.headers.setdefault("X-XSS-Protection", "1; mode=block")
    return response


def json_error(message, status=400):
    """Consistent structured JSON error response used by every Milestone 4 API."""
    return jsonify({"success": False, "error": message}), status


def login_required(role=None):
    def decorator(f):
        from functools import wraps

        @wraps(f)
        def wrapped(*args, **kwargs):
            if "admin_id" not in session:
                flash("Please log in to continue.", "error")
                return redirect(url_for("login"))
            if role and session.get("role") != role and session.get("role") != "admin":
                flash("You do not have permission to view that page.", "error")
                return redirect(url_for("dashboard"))
            return f(*args, **kwargs)
        return wrapped
    return decorator


@app.context_processor
def inject_operations_constants():
    """Make Milestone 2 reference lists available in every template
    without each route having to pass them explicitly."""
    return {
        "FACILITIES_LIST": ops.FACILITIES_LIST,
        "ROOM_TYPES": ops.ROOM_TYPES,
        "SESSION_TYPES": ops.SESSION_TYPES,
        "SESSION_STATUSES": ops.SESSION_STATUSES,
        "VENUE_STATUSES": ops.VENUE_STATUSES,
    }


@app.context_processor
def inject_milestone3_constants():
    """Make Milestone 3 (Sponsorship & Incident) reference lists — and the
    live unread alert count for the nav badge — available everywhere."""
    alert_counts = {}
    if session.get("admin_id"):
        try:
            alert_counts = alerts.get_alert_counts()
        except Exception:
            alert_counts = {}
    return {
        "INDUSTRIES": spx.INDUSTRIES,
        "SPONSORSHIP_CATEGORIES": spx.SPONSORSHIP_CATEGORIES,
        "BUDGET_LEVELS": spx.BUDGET_LEVELS,
        "SPONSOR_STATUSES": spx.SPONSOR_STATUSES,
        "COMMUNICATION_METHODS": spx.COMMUNICATION_METHODS,
        "OPPORTUNITY_STATUSES": spx.OPPORTUNITY_STATUSES,
        "INCIDENT_CATEGORIES": inc.CATEGORIES,
        "INCIDENT_PRIORITIES": inc.PRIORITIES,
        "INCIDENT_STATUSES": inc.STATUSES,
        "alert_counts": alert_counts,
    }


def refresh_all_alerts():
    """Re-scan sponsorship and incident state and raise any new operational
    alerts. Called on dashboard-style pages so alerts stay current without
    running on every single request."""
    try:
        spx.refresh_sponsorship_alerts()
        inc.refresh_incident_alerts()
    except Exception as e:
        print("[app.py] Alert refresh skipped/failed:", e)


# =================================================================
# STATIC PAGES
# =================================================================
@app.route("/")
def index():
    stats = db.query_one("SELECT COUNT(*) as total FROM users")
    return render_template("index.html", total=stats["total"] if stats else 0)


@app.route("/about")
def about():
    return render_template("about.html")


@app.route("/contact", methods=["GET", "POST"])
def contact():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        email = request.form.get("email", "").strip()
        subject = request.form.get("subject", "").strip()
        message = request.form.get("message", "").strip()

        if not name or not email or not message:
            flash("Please fill in all required fields.", "error")
            return redirect(url_for("contact"))
        if not EMAIL_REGEX.match(email):
            flash("Please enter a valid email address.", "error")
            return redirect(url_for("contact"))

        db.execute(
            "INSERT INTO contacts (name, email, subject, message) VALUES (?, ?, ?, ?)",
            (name, email, subject, message),
        )
        flash("Your message has been sent successfully! We will get back to you soon.", "success")
        return redirect(url_for("contact"))

    return render_template("contact.html")


# =================================================================
# REGISTRATION
# =================================================================
@app.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        data = {
            "name": request.form.get("name", "").strip(),
            "email": request.form.get("email", "").strip().lower(),
            "phone": request.form.get("phone", "").strip(),
            "college": request.form.get("college", "").strip(),
            "department": request.form.get("department", "").strip(),
            "gender": request.form.get("gender", "").strip(),
            "city": request.form.get("city", "").strip(),
            "participant_category": request.form.get("participant_category", "").strip(),
            "attendance_mode": request.form.get("attendance_mode", "").strip(),
        }

        errors = validate_registration(data)
        if errors:
            for e in errors:
                flash(e, "error")
            return render_template("register.html", form_data=data, categories=PARTICIPANT_CATEGORIES)

        existing = db.query_one("SELECT id FROM users WHERE email = ?", (data["email"],))
        if existing:
            flash("This email is already registered. Duplicate registrations are not allowed.", "error")
            return render_template("register.html", form_data=data, categories=PARTICIPANT_CATEGORIES)

        user_id = db.execute(
            """INSERT INTO users (name, email, phone, college, department, gender,
               city, participant_category, attendance_mode) VALUES (?,?,?,?,?,?,?,?,?)""",
            (data["name"], data["email"], data["phone"], data["college"], data["department"],
             data["gender"], data["city"], data["participant_category"],
             data["attendance_mode"]),
        )

        registration_id = generate_registration_id(user_id)
        user_row = db.query_one("SELECT * FROM users WHERE id = ?", (user_id,))
        qr_data = build_qr_payload({**user_row, "registration_id": registration_id})
        db.execute(
            "UPDATE users SET registration_id = ?, qr_code = ? WHERE id = ?",
            (registration_id, qr_data, user_id),
        )

        flash("Registration successful! Your Registration ID is {}".format(registration_id), "success")
        return redirect(url_for("register_success", user_id=user_id))

    return render_template("register.html", form_data={}, categories=PARTICIPANT_CATEGORIES)


@app.route("/register/success/<int:user_id>")
def register_success(user_id):
    user = db.query_one("SELECT * FROM users WHERE id = ?", (user_id,))
    if not user:
        return redirect(url_for("register"))

    qr_base64 = None
    if qrcode:
        buf = generate_qr_image_bytes(user["qr_code"] or build_qr_payload(user))
        if buf:
            qr_base64 = f"data:image/png;base64,{base64.b64encode(buf.read()).decode('utf-8')}"

    return render_template(
        "register.html", success_user=user, qr_base64=qr_base64,
        form_data={}, categories=PARTICIPANT_CATEGORIES,
    )


@app.route("/register/pass/<int:user_id>/pdf")
def register_pass_pdf(user_id):
    user = db.query_one("SELECT * FROM users WHERE id = ?", (user_id,))
    if not user:
        return redirect(url_for("register"))

    try:
        from reportlab.lib.pagesizes import A6
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER
    except ImportError:
        return "PDF generation requires 'reportlab'. Run: pip install reportlab", 500

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A6, topMargin=14 * mm, bottomMargin=14 * mm,
                             leftMargin=10 * mm, rightMargin=10 * mm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("PassTitle", parent=styles["Title"], fontSize=15,
                                  textColor=colors.HexColor("#6C5CE7"), alignment=TA_CENTER)
    center_style = ParagraphStyle("PassCenter", parent=styles["Normal"], alignment=TA_CENTER)

    elements = [
        Paragraph("RegisterAI — Event Pass", title_style),
        Spacer(1, 10),
    ]

    qr_buf = generate_qr_image_bytes(user["qr_code"] or build_qr_payload(user))
    if qr_buf:
        elements.append(Image(qr_buf, width=45 * mm, height=45 * mm, hAlign="CENTER"))
        elements.append(Spacer(1, 10))

    elements.append(Paragraph(f"<b>{user['name']}</b>", center_style))
    elements.append(Paragraph(user["registration_id"] or f"Attendee #{user['id']}", center_style))
    elements.append(Spacer(1, 10))

    details = [
        ["Category", user["participant_category"]],
        ["Email", user["email"]],
        ["Phone", user["phone"]],
        ["Mode", user["attendance_mode"]],
    ]
    table = Table(details, colWidths=[35 * mm, 55 * mm])
    table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6C5CE7")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -1), 0.4, colors.HexColor("#EAEAF5")),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("Please bring this pass (printed or on-screen) to the check-in desk.",
                               ParagraphStyle("Note", parent=styles["Normal"], fontSize=7.5,
                                              alignment=TA_CENTER, textColor=colors.grey)))

    doc.build(elements)
    buf.seek(0)
    filename = f"{user['registration_id'] or user_id}_pass.pdf"
    return send_file(buf, mimetype="application/pdf", as_attachment=True, download_name=filename)


def validate_registration(data):
    errors = []
    required_fields = ["name", "email", "phone", "college", "department",
                        "gender", "city", "participant_category", "attendance_mode"]
    for field in required_fields:
        if not data.get(field):
            errors.append(f"'{field.replace('_',' ').title()}' is required.")

    if data.get("participant_category") and data["participant_category"] not in PARTICIPANT_CATEGORIES:
        errors.append("Please select a valid Participant Category.")

    if data.get("email") and not EMAIL_REGEX.match(data["email"]):
        errors.append("Please enter a valid email address.")

    if data.get("phone") and not PHONE_REGEX.match(data["phone"]):
        errors.append("Please enter a valid 10-digit Indian phone number starting with 6-9.")

    return errors


@app.route("/api/check-email")
def api_check_email():
    email = request.args.get("email", "").strip().lower()
    exists = db.query_one("SELECT id FROM users WHERE email = ?", (email,))
    return jsonify({"exists": bool(exists)})


# =================================================================
# AUTH
# =================================================================
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")
        role = request.form.get("role", "admin")

        admin = db.query_one("SELECT * FROM admins WHERE email = ? AND role = ?", (email, role))
        if admin and check_password_hash(admin["password"], password):
            session["admin_id"] = admin["id"]
            session["admin_name"] = admin["name"]
            session["role"] = admin["role"]
            flash(f"Welcome back, {admin['name']}!", "success")
            return redirect(url_for("dashboard"))

        flash("Invalid credentials. Please try again.", "error")
        return render_template("login.html")

    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    flash("You have been logged out successfully.", "success")
    return redirect(url_for("login"))


# =================================================================
# ADMIN DASHBOARD
# =================================================================
@app.route("/dashboard")
@login_required()
def dashboard():
    users = db.query_all("SELECT * FROM users ORDER BY created_at DESC")
    total = len(users)
    today_str = datetime.now().strftime("%Y-%m-%d")
    today_count = sum(1 for u in users if str(u.get("created_at", "")).startswith(today_str))

    male = sum(1 for u in users if u.get("gender", "").lower() == "male")
    female = sum(1 for u in users if u.get("gender", "").lower() == "female")
    other = total - male - female

    departments = len(set(u.get("department") for u in users))
    cities = len(set(u.get("city") for u in users))

    attendance_pred = ai_model.predict_attendance_percentage(users)
    ai_summary = ai_model.generate_ai_summary(users)

    refresh_all_alerts()
    m3 = {
        "potential_sponsors": db.query_one(
            "SELECT COUNT(*) as c FROM sponsors WHERE status IN ('Discovered','Potential','Shortlisted','Ready to Contact')"
        )["c"],
        "followups_due": len(spx.get_followup_buckets()["due_today"]) + len(spx.get_followup_buckets()["overdue"]),
        "confirmed_sponsors": db.query_one("SELECT COUNT(*) as c FROM sponsors WHERE status = 'Confirmed'")["c"],
        "open_incidents": db.query_one(
            "SELECT COUNT(*) as c FROM incidents WHERE status IN ('Reported','Assigned','In Progress')"
        )["c"],
        "critical_incidents": db.query_one("SELECT COUNT(*) as c FROM incidents WHERE priority = 'Critical'")["c"],
        "open_alerts": alerts.get_alert_counts()["total"],
    }

    return render_template(
        "dashboard.html",
        total=total, today_count=today_count, male=male, female=female, other=other,
        departments=departments, cities=cities,
        attendance_pred=attendance_pred, ai_summary=ai_summary,
        recent_users=users[:6], m3=m3,
    )


def get_category_counts(users):
    """Return an OrderedDict-like list of (category, count) for every
    Participant Category, in the canonical PARTICIPANT_CATEGORIES order."""
    from collections import Counter
    counter = Counter(u.get("participant_category", "N/A") for u in users)
    return [(cat, counter.get(cat, 0)) for cat in PARTICIPANT_CATEGORIES]


@app.route("/attendees")
@login_required()
def attendees():
    users = db.query_all("SELECT * FROM users ORDER BY created_at DESC")
    return render_template("attendees.html", users=users)


@app.route("/api/attendees/<int:user_id>", methods=["PUT", "DELETE"])
@login_required()
def api_attendee_detail(user_id):
    if request.method == "DELETE":
        db.execute("DELETE FROM users WHERE id = ?", (user_id,))
        return jsonify({"success": True, "message": "Attendee deleted successfully."})

    data = request.get_json(force=True)
    fields = ["name", "email", "phone", "college", "department",
              "gender", "city", "participant_category", "attendance_mode"]
    updates = {k: v for k, v in data.items() if k in fields}
    if not updates:
        return jsonify({"success": False, "message": "No valid fields to update."}), 400

    set_clause = ", ".join(f"{k} = ?" for k in updates)
    params = list(updates.values()) + [user_id]
    db.execute(f"UPDATE users SET {set_clause} WHERE id = ?", params)
    return jsonify({"success": True, "message": "Attendee updated successfully."})


@app.route("/api/attendees")
@login_required()
def api_attendees_list():
    users = db.query_all("SELECT * FROM users ORDER BY created_at DESC")
    return jsonify(users)


@app.route("/attendees/export/csv")
@login_required()
def export_csv():
    users = db.query_all("SELECT * FROM users ORDER BY created_at DESC")
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["ID", "Registration ID", "Name", "Email", "Phone", "College", "Department",
                      "Gender", "City", "Participant Category", "Attendance Mode", "Checked In", "Registered At"])
    for u in users:
        writer.writerow([u["id"], u["registration_id"], u["name"], u["email"], u["phone"], u["college"],
                          u["department"], u["gender"], u["city"], u["participant_category"],
                          u["attendance_mode"], "Yes" if u["checked_in"] else "No",
                          u["created_at"]])
    output.seek(0)
    return Response(
        output.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": "attachment; filename=attendees_export.csv"},
    )


# =================================================================
# QR CHECK-IN
# =================================================================
@app.route("/checkin")
@login_required()
def checkin():
    users = db.query_all("""
        SELECT u.*,
               (SELECT check_in_time FROM attendance WHERE user_id = u.id
                ORDER BY check_in_time DESC LIMIT 1) AS check_in_time
        FROM users u ORDER BY u.created_at DESC
    """)
    checked_in_count = sum(1 for u in users if u["checked_in"])
    return render_template("checkin.html", users=users, checked_in_count=checked_in_count, total=len(users))


@app.route("/api/qrcode/<int:user_id>")
def api_qrcode(user_id):
    user = db.query_one("SELECT * FROM users WHERE id = ?", (user_id,))
    if not user or not qrcode:
        return jsonify({"error": "QR generation unavailable"}), 400

    buf = generate_qr_image_bytes(user["qr_code"] or build_qr_payload(user))
    encoded = base64.b64encode(buf.read()).decode("utf-8")
    return jsonify({"qr_base64": f"data:image/png;base64,{encoded}"})


@app.route("/api/qrcode/<int:user_id>/download")
def api_qrcode_download(user_id):
    user = db.query_one("SELECT * FROM users WHERE id = ?", (user_id,))
    if not user or not qrcode:
        return jsonify({"error": "QR generation unavailable"}), 400

    buf = generate_qr_image_bytes(user["qr_code"] or build_qr_payload(user))
    filename = f"{user['registration_id'] or user_id}_qrcode.png"
    return send_file(buf, mimetype="image/png", as_attachment=True, download_name=filename)


@app.route("/api/checkin", methods=["POST"])
@login_required()
def api_checkin():
    data = request.get_json(force=True)
    code = data.get("code", "").strip()

    user = find_user_by_scan_code(code)

    if not user:
        return jsonify({"success": False, "message": "Invalid code / attendee not found."}), 404

    if user["checked_in"]:
        return jsonify({"success": False, "message": f"{user['name']} is already checked in."})

    db.execute("UPDATE users SET checked_in = 1 WHERE id = ?", (user["id"],))
    db.execute("INSERT INTO attendance (user_id, status) VALUES (?, 'Present')", (user["id"],))

    checkin_row = db.query_one(
        "SELECT check_in_time FROM attendance WHERE user_id = ? ORDER BY check_in_time DESC LIMIT 1",
        (user["id"],),
    )
    user["check_in_time"] = checkin_row["check_in_time"] if checkin_row else None
    user["checked_in"] = 1

    total = db.query_one("SELECT COUNT(*) as c FROM users")["c"]
    checked_in = db.query_one("SELECT COUNT(*) as c FROM users WHERE checked_in = 1")["c"]

    return jsonify({
        "success": True,
        "message": f"{user['name']} checked in successfully!",
        "user": user,
        "checked_in_count": checked_in,
        "total": total,
    })


# =================================================================
# AI ANALYTICS
# =================================================================
@app.route("/analytics")
@login_required()
def analytics():
    users = db.query_all("SELECT * FROM users ORDER BY created_at DESC")
    insights = ai_model.generate_organizer_insights(users)
    recommendations = ai_model.recommend_event_planning(users)
    no_shows = ai_model.predict_no_shows(users)[:10]
    attendance_pred = ai_model.predict_attendance_percentage(users)
    ai_summary = ai_model.generate_ai_summary(users)
    trend = ai_model.get_registration_trend(users)

    return render_template(
        "analytics.html",
        insights=insights, recommendations=recommendations, no_shows=no_shows,
        attendance_pred=attendance_pred, ai_summary=ai_summary, trend=trend,
        total=len(users), category_counts=get_category_counts(users),
    )


@app.route("/api/charts/overview")
@login_required()
def api_charts_overview():
    users = db.query_all("SELECT * FROM users")

    from collections import Counter
    dept = Counter(u["department"] for u in users)
    gender = Counter(u["gender"] for u in users)
    cities = Counter(u["city"] for u in users)
    trend = ai_model.get_registration_trend(users)
    category_pairs = get_category_counts(users)

    return jsonify({
        "departments": {"labels": list(dept.keys()), "data": list(dept.values())},
        "gender": {"labels": list(gender.keys()), "data": list(gender.values())},
        "categories": {"labels": [c for c, _ in category_pairs], "data": [n for _, n in category_pairs]},
        "cities": {"labels": list(cities.keys()), "data": list(cities.values())},
        "trend": trend,
    })


# =================================================================
# REPORTS
# =================================================================
@app.route("/reports")
@login_required()
def reports():
    users = db.query_all("SELECT * FROM users")
    return render_template("reports.html", total=len(users), category_counts=get_category_counts(users))


@app.route("/reports/download/csv")
@login_required()
def download_report_csv():
    return export_csv()


@app.route("/reports/download/pdf")
@login_required()
def download_report_pdf():
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
    except ImportError:
        return "PDF generation requires 'reportlab'. Run: pip install reportlab", 500

    users = db.query_all("SELECT * FROM users ORDER BY created_at DESC")
    ai_summary = ai_model.generate_ai_summary(users)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("AI-Powered Registration Intelligence Report", styles["Title"]))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%d %b %Y, %H:%M')}", styles["Normal"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("<b>AI Summary</b>", styles["Heading2"]))
    elements.append(Paragraph(ai_summary, styles["Normal"]))
    elements.append(Spacer(1, 16))
    elements.append(Paragraph("<b>Attendee List</b>", styles["Heading2"]))

    table_data = [["ID", "Reg. ID", "Name", "Email", "Dept", "Category", "Mode"]]
    for u in users[:200]:
        table_data.append([u["id"], u["registration_id"], u["name"], u["email"], u["department"],
                            u["participant_category"], u["attendance_mode"]])

    table = Table(table_data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6C5CE7")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F3F1FE")]),
    ]))
    elements.append(table)
    doc.build(elements)
    buf.seek(0)

    db.execute("INSERT INTO reports (report_type, generated_by, file_path) VALUES (?,?,?)",
               ("PDF", session.get("admin_name", "system"), "generated_in_memory"))

    return send_file(buf, mimetype="application/pdf", as_attachment=True,
                      download_name="registration_report.pdf")


# =================================================================
# MILESTONE 2 — VENUE MANAGEMENT / VENUE AGENT
# =================================================================
def validate_venue(data):
    errors = []
    if not data.get("name"):
        errors.append("Venue name is required.")
    try:
        cap = int(data.get("capacity") or 0)
        if cap <= 0:
            errors.append("Venue capacity must be a valid positive number.")
    except (TypeError, ValueError):
        errors.append("Venue capacity must be a valid number.")
    return errors


@app.route("/venues")
@login_required()
def venues_page():
    venues = db.query_all("SELECT * FROM venues ORDER BY name ASC")
    for v in venues:
        v["facilities_list"] = ops.parse_csv_field(v["facilities"])
        v["live_status"] = ops.venue_status_today(v["id"]) or v["status"]
        v["booking_count"] = db.query_one(
            "SELECT COUNT(*) as c FROM sessions WHERE venue_id = ? AND status != 'Cancelled'", (v["id"],)
        )["c"]
        v["next_available"] = ops.get_next_available_label(v["id"])
    locations = sorted(set(v["location"] for v in venues if v["location"]))
    return render_template("venues.html", venues=venues, locations=locations)


@app.route("/api/venues/search")
@login_required()
def api_venues_search():
    filters = {
        "q": request.args.get("q", ""),
        "capacity_min": request.args.get("capacity_min", ""),
        "location": request.args.get("location", ""),
        "room_type": request.args.get("room_type", ""),
        "availability": request.args.get("availability", "All"),
        "facilities": [f for f in request.args.get("facilities", "").split(",") if f],
        "date": request.args.get("date", ""),
        "start_time": request.args.get("start_time", ""),
        "end_time": request.args.get("end_time", ""),
        "attendees": request.args.get("attendees", ""),
        "sort": request.args.get("sort", "name"),
    }
    results = ops.search_venues(filters)
    payload = []
    for r in results:
        v = dict(r["venue"])
        v["facilities_list"] = r["facilities_list"]
        v["availability_status"] = r["availability_status"]
        v["booking_count"] = r["booking_count"]
        v["next_available"] = r["next_available"]
        v["score"] = r["score"]
        payload.append(v)
    return jsonify(payload)


@app.route("/api/venues/<int:venue_id>/details")
@login_required()
def api_venue_full_details(venue_id):
    details = ops.get_venue_details(venue_id)
    if not details:
        return jsonify({"success": False, "message": "Venue not found."}), 404
    return jsonify({"success": True, **details})


@app.route("/api/venues", methods=["GET", "POST"])
@login_required()
def api_venues():
    if request.method == "GET":
        return jsonify(db.query_all("SELECT * FROM venues ORDER BY name ASC"))

    data = request.get_json(force=True)
    errors = validate_venue(data)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors)}), 400

    facilities = ",".join(data.get("facilities") or [])
    venue_id = db.execute(
        """INSERT INTO venues (name, location, capacity, room_type, facilities, status)
           VALUES (?,?,?,?,?,?)""",
        (data["name"], data.get("location", ""), int(data["capacity"]),
         data.get("room_type", ""), facilities, data.get("status", "Available")),
    )
    return jsonify({"success": True, "message": "Venue added successfully.", "id": venue_id})


@app.route("/api/venues/<int:venue_id>", methods=["PUT", "DELETE"])
@login_required()
def api_venue_detail(venue_id):
    if request.method == "DELETE":
        db.execute("DELETE FROM venues WHERE id = ?", (venue_id,))
        return jsonify({"success": True, "message": "Venue deleted successfully."})

    data = request.get_json(force=True)
    errors = validate_venue(data)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors)}), 400

    facilities = ",".join(data.get("facilities") or [])
    db.execute(
        """UPDATE venues SET name=?, location=?, capacity=?, room_type=?, facilities=?, status=?
           WHERE id=?""",
        (data["name"], data.get("location", ""), int(data["capacity"]),
         data.get("room_type", ""), facilities, data.get("status", "Available"), venue_id),
    )
    return jsonify({"success": True, "message": "Venue updated successfully."})


@app.route("/api/venues/<int:venue_id>/book", methods=["POST"])
@login_required()
def api_book_venue(venue_id):
    """Quick 'Book Venue' action from the Venue Management page — creates a
    session tied to this venue, running the same conflict validation used by
    full Session Management."""
    data = request.get_json(force=True)
    title = (data.get("title") or "").strip()
    session_date = data.get("session_date", "")
    start_time = data.get("start_time", "")
    end_time = data.get("end_time", "")
    attendees = int(data.get("expected_attendees") or 0)

    if not title or not session_date or not start_time or not end_time:
        return jsonify({"success": False, "message": "Title, date, start time and end time are required."}), 400

    errors = ops.validate_session_slot(venue_id, None, session_date, start_time, end_time, expected_attendees=attendees)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors), "conflict": True}), 409

    session_id = db.execute(
        """INSERT INTO sessions (title, description, session_type, session_date, start_time, end_time,
           expected_attendees, required_facilities, venue_id, speaker_id, status)
           VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
        (title, data.get("description", ""), data.get("session_type", ""), session_date, start_time, end_time,
         attendees, "", venue_id, None, "Scheduled"),
    )
    return jsonify({"success": True, "message": "Venue booked successfully.", "id": session_id})


@app.route("/venue-agent", methods=["GET", "POST"])
@login_required()
def venue_agent():
    results = None
    requirements = {}
    if request.method == "POST":
        requirements = {
            "attendees": request.form.get("attendees", "0"),
            "facilities": request.form.getlist("facilities"),
            "session_type": request.form.get("session_type", ""),
            "session_date": request.form.get("session_date", ""),
            "start_time": request.form.get("start_time", ""),
            "end_time": request.form.get("end_time", ""),
        }
        results = ops.recommend_venues(requirements)
    return render_template("venue_agent.html", results=results, requirements=requirements)


# =================================================================
# MILESTONE 2 — SPEAKER MANAGEMENT / SPEAKER AGENT
# =================================================================
def validate_speaker(data):
    errors = []
    if not data.get("name"):
        errors.append("Speaker name is required.")
    if data.get("email") and not EMAIL_REGEX.match(data["email"]):
        errors.append("Please enter a valid speaker email address.")
    return errors


@app.route("/speakers")
@login_required()
def speakers_page():
    speakers = db.query_all("SELECT * FROM speakers ORDER BY name ASC")
    for s in speakers:
        s["expertise_list"] = ops.parse_csv_field(s["expertise"])
        s["available_dates_list"] = ops.parse_csv_field(s["available_dates"])
        s["assigned_count"] = db.query_one(
            "SELECT COUNT(*) as c FROM sessions WHERE speaker_id = ? AND status != 'Cancelled'", (s["id"],)
        )["c"]
    return render_template("speakers.html", speakers=speakers)


@app.route("/api/speakers", methods=["GET", "POST"])
@login_required()
def api_speakers():
    if request.method == "GET":
        return jsonify(db.query_all("SELECT * FROM speakers ORDER BY name ASC"))

    data = request.get_json(force=True)
    errors = validate_speaker(data)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors)}), 400

    speaker_id = db.execute(
        """INSERT INTO speakers (name, email, phone, organization, designation, expertise,
           bio, preferred_session_type, available_dates, available_slots)
           VALUES (?,?,?,?,?,?,?,?,?,?)""",
        (data["name"], data.get("email", ""), data.get("phone", ""), data.get("organization", ""),
         data.get("designation", ""), data.get("expertise", ""), data.get("bio", ""),
         data.get("preferred_session_type", ""), data.get("available_dates", ""),
         data.get("available_slots", "")),
    )
    return jsonify({"success": True, "message": "Speaker added successfully.", "id": speaker_id})


@app.route("/api/speakers/<int:speaker_id>", methods=["PUT", "DELETE"])
@login_required()
def api_speaker_detail(speaker_id):
    if request.method == "DELETE":
        db.execute("DELETE FROM speakers WHERE id = ?", (speaker_id,))
        return jsonify({"success": True, "message": "Speaker deleted successfully."})

    data = request.get_json(force=True)
    errors = validate_speaker(data)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors)}), 400

    db.execute(
        """UPDATE speakers SET name=?, email=?, phone=?, organization=?, designation=?, expertise=?,
           bio=?, preferred_session_type=?, available_dates=?, available_slots=? WHERE id=?""",
        (data["name"], data.get("email", ""), data.get("phone", ""), data.get("organization", ""),
         data.get("designation", ""), data.get("expertise", ""), data.get("bio", ""),
         data.get("preferred_session_type", ""), data.get("available_dates", ""),
         data.get("available_slots", ""), speaker_id),
    )
    return jsonify({"success": True, "message": "Speaker updated successfully."})


@app.route("/speaker-agent", methods=["GET", "POST"])
@login_required()
def speaker_agent():
    results = None
    requirements = {}
    if request.method == "POST":
        requirements = {
            "topic": request.form.get("topic", ""),
            "session_type": request.form.get("session_type", ""),
            "session_date": request.form.get("session_date", ""),
            "start_time": request.form.get("start_time", ""),
            "end_time": request.form.get("end_time", ""),
        }
        results = ops.recommend_speakers(requirements)
    return render_template("speaker_agent.html", results=results, requirements=requirements)


# =================================================================
# MILESTONE 2 — SESSION MANAGEMENT & INTELLIGENT SCHEDULING
# =================================================================
def _session_payload(data):
    return {
        "title": (data.get("title") or "").strip(),
        "description": (data.get("description") or "").strip(),
        "session_type": data.get("session_type", ""),
        "session_date": data.get("session_date", ""),
        "start_time": data.get("start_time", ""),
        "end_time": data.get("end_time", ""),
        "expected_attendees": int(data.get("expected_attendees") or 0),
        "required_facilities": data.get("required_facilities") or [],
        "venue_id": int(data["venue_id"]) if data.get("venue_id") else None,
        "speaker_id": int(data["speaker_id"]) if data.get("speaker_id") else None,
        "status": data.get("status", "Scheduled"),
    }


def _sessions_with_names():
    rows = db.query_all("""
        SELECT s.*, v.name as venue_name, v.capacity as venue_capacity,
               sp.name as speaker_name
        FROM sessions s
        LEFT JOIN venues v ON s.venue_id = v.id
        LEFT JOIN speakers sp ON s.speaker_id = sp.id
        ORDER BY s.session_date ASC, s.start_time ASC
    """)
    for r in rows:
        r["required_facilities_list"] = ops.parse_csv_field(r["required_facilities"])
    return rows


@app.route("/sessions")
@login_required()
def sessions_page():
    sessions = _sessions_with_names()
    venues = db.query_all("SELECT * FROM venues WHERE status != 'Maintenance' ORDER BY name ASC")
    speakers = db.query_all("SELECT * FROM speakers ORDER BY name ASC")
    return render_template("sessions.html", sessions=sessions, venues=venues, speakers=speakers)


@app.route("/api/sessions", methods=["GET", "POST"])
@login_required()
def api_sessions():
    if request.method == "GET":
        return jsonify(_sessions_with_names())

    data = request.get_json(force=True)
    if not data.get("title") or not data.get("session_date") or not data.get("start_time") or not data.get("end_time"):
        return jsonify({"success": False, "message": "Title, date, start time and end time are required."}), 400

    payload = _session_payload(data)
    errors = ops.validate_session_slot(
        payload["venue_id"], payload["speaker_id"], payload["session_date"],
        payload["start_time"], payload["end_time"],
        expected_attendees=payload["expected_attendees"],
        required_facilities=payload["required_facilities"],
    )
    if errors:
        return jsonify({"success": False, "message": " ".join(errors), "conflict": True}), 409

    session_id = db.execute(
        """INSERT INTO sessions (title, description, session_type, session_date, start_time, end_time,
           expected_attendees, required_facilities, venue_id, speaker_id, status)
           VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
        (payload["title"], payload["description"], payload["session_type"], payload["session_date"],
         payload["start_time"], payload["end_time"], payload["expected_attendees"],
         ",".join(payload["required_facilities"]), payload["venue_id"], payload["speaker_id"],
         payload["status"]),
    )
    return jsonify({"success": True, "message": "Session created and allocation confirmed.", "id": session_id})


@app.route("/api/sessions/<int:session_id>", methods=["PUT", "DELETE"])
@login_required()
def api_session_detail(session_id):
    if request.method == "DELETE":
        db.execute("DELETE FROM sessions WHERE id = ?", (session_id,))
        return jsonify({"success": True, "message": "Session removed successfully."})

    data = request.get_json(force=True)
    payload = _session_payload(data)
    errors = ops.validate_session_slot(
        payload["venue_id"], payload["speaker_id"], payload["session_date"],
        payload["start_time"], payload["end_time"],
        expected_attendees=payload["expected_attendees"],
        required_facilities=payload["required_facilities"],
        exclude_session_id=session_id,
    )
    if errors:
        return jsonify({"success": False, "message": " ".join(errors), "conflict": True}), 409

    db.execute(
        """UPDATE sessions SET title=?, description=?, session_type=?, session_date=?, start_time=?,
           end_time=?, expected_attendees=?, required_facilities=?, venue_id=?, speaker_id=?, status=?
           WHERE id=?""",
        (payload["title"], payload["description"], payload["session_type"], payload["session_date"],
         payload["start_time"], payload["end_time"], payload["expected_attendees"],
         ",".join(payload["required_facilities"]), payload["venue_id"], payload["speaker_id"],
         payload["status"], session_id),
    )
    return jsonify({"success": True, "message": "Session updated successfully."})


@app.route("/scheduler")
@login_required()
def scheduler():
    selected_date = request.args.get("date") or datetime.now().strftime("%Y-%m-%d")
    all_sessions = _sessions_with_names()
    day_sessions = [s for s in all_sessions if s["session_date"] == selected_date]
    day_sessions.sort(key=lambda s: s["start_time"])

    venues = db.query_all("SELECT * FROM venues ORDER BY name ASC")
    venue_rows = []
    for v in venues:
        v_sessions = [s for s in day_sessions if s["venue_id"] == v["id"]]
        venue_rows.append({"venue": v, "sessions": v_sessions})

    upcoming_dates = sorted(set(s["session_date"] for s in all_sessions if s["session_date"] >= selected_date))[:14]

    return render_template(
        "scheduler.html", selected_date=selected_date, day_sessions=day_sessions,
        venue_rows=venue_rows, all_sessions=all_sessions, upcoming_dates=upcoming_dates,
    )


# =================================================================
# MILESTONE 2 — SESSION ANALYTICS
# =================================================================
@app.route("/analytics/operations")
@login_required()
def operations_analytics():
    stats = ops.generate_operations_analytics()
    return render_template("operations_analytics.html", stats=stats)


@app.route("/api/charts/operations")
@login_required()
def api_charts_operations():
    stats = ops.generate_operations_analytics()
    return jsonify(stats["charts"])


# =================================================================
# PUBLIC SESSION SCHEDULE (attendee / speaker facing)
# =================================================================
@app.route("/schedule")
def public_schedule():
    sessions = db.query_all("""
        SELECT s.*, v.name as venue_name, v.location as venue_location,
               sp.name as speaker_name, sp.organization as speaker_org, sp.designation as speaker_designation
        FROM sessions s
        LEFT JOIN venues v ON s.venue_id = v.id
        LEFT JOIN speakers sp ON s.speaker_id = sp.id
        WHERE s.status != 'Cancelled'
        ORDER BY s.session_date ASC, s.start_time ASC
    """)
    dates = sorted(set(s["session_date"] for s in sessions))
    return render_template("schedule.html", sessions=sessions, dates=dates)


# =================================================================
# MILESTONE 3 — SPONSORSHIP & INCIDENT MANAGEMENT
# =================================================================
@app.route("/milestone3")
@login_required()
def milestone3_dashboard():
    refresh_all_alerts()
    perf = spx.get_performance_stats()
    inc_stats = inc.get_dashboard_stats()
    followups = spx.get_followup_buckets()
    recent_alerts = alerts.get_alerts()[:6]
    return render_template(
        "milestone3_dashboard.html", perf=perf, inc_stats=inc_stats,
        followups=followups, recent_alerts=recent_alerts,
    )


# -----------------------------------------------------------------
# Sponsorship Agent (suitability scoring & ranked recommendations)
# -----------------------------------------------------------------
@app.route("/sponsor-agent", methods=["GET", "POST"])
@login_required()
def sponsor_agent():
    industry_filter = request.values.get("industry", "")
    sponsors = db.query_all("SELECT * FROM sponsors ORDER BY company_name ASC")
    if industry_filter:
        sponsors = [s for s in sponsors if (s["industry"] or "") == industry_filter]

    results = []
    for s in sponsors:
        score, match_category, explanation, reasons = spx.score_sponsor(s)
        results.append({
            "sponsor": s, "score": score, "match_category": match_category,
            "explanation": explanation, "reasons": reasons,
        })
    results.sort(key=lambda r: -r["score"])
    return render_template("sponsor_agent.html", results=results, industry_filter=industry_filter)


@app.route("/api/sponsors/<int:sponsor_id>/evaluate", methods=["POST"])
@login_required()
def api_evaluate_sponsor(sponsor_id):
    result = spx.evaluate_and_save_score(sponsor_id)
    if not result:
        return jsonify({"success": False, "message": "Sponsor not found."}), 404
    return jsonify({"success": True, **result})


# -----------------------------------------------------------------
# Sponsor Discovery / Directory & Status Management
# -----------------------------------------------------------------
def validate_sponsor(data):
    errors = []
    if not (data.get("company_name") or "").strip():
        errors.append("Company name is required.")
    if data.get("contact_email") and not EMAIL_REGEX.match(data["contact_email"]):
        errors.append("Please enter a valid sponsor contact email address.")
    return errors


@app.route("/sponsors")
@login_required()
def sponsors_page():
    filters = {
        "q": request.args.get("q", ""), "industry": request.args.get("industry", ""),
        "location": request.args.get("location", ""), "category": request.args.get("category", ""),
        "budget": request.args.get("budget", ""), "status": request.args.get("status", ""),
        "sort": request.args.get("sort", "score_desc"),
    }
    sponsors = spx.search_sponsors(filters)
    locations = sorted(set(s["location"] for s in db.query_all("SELECT DISTINCT location FROM sponsors") if s["location"]))
    return render_template("sponsors.html", sponsors=sponsors, locations=locations, filters=filters)


@app.route("/api/sponsors", methods=["GET", "POST"])
@login_required()
def api_sponsors():
    if request.method == "GET":
        return jsonify(db.query_all("SELECT * FROM sponsors ORDER BY company_name ASC"))

    data = request.get_json(force=True)
    errors = validate_sponsor(data)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors)}), 400

    sponsor_id = db.execute(
        """INSERT INTO sponsors (company_name, industry, website, location, target_audience, keywords,
           sponsorship_category, budget_potential, estimated_budget, contact_person, contact_email,
           contact_phone, status, source, notes)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
        (data["company_name"], data.get("industry", ""), data.get("website", ""), data.get("location", ""),
         data.get("target_audience", ""), data.get("keywords", ""), data.get("sponsorship_category", ""),
         data.get("budget_potential", "Medium"), int(data.get("estimated_budget") or 0),
         data.get("contact_person", ""), data.get("contact_email", ""), data.get("contact_phone", ""),
         data.get("status", "Discovered"), data.get("source", "Manual Entry"), data.get("notes", "")),
    )
    spx.log_interaction(sponsor_id, "Discovery", "System", "Sponsor discovered/recorded",
                         f"Sponsor added to the directory via {data.get('source', 'Manual Entry')}.")
    spx.evaluate_and_save_score(sponsor_id)
    return jsonify({"success": True, "message": "Sponsor added successfully.", "id": sponsor_id})


@app.route("/api/sponsors/<int:sponsor_id>", methods=["GET", "PUT", "DELETE"])
@login_required()
def api_sponsor_detail(sponsor_id):
    if request.method == "GET":
        sponsor = db.query_one("SELECT * FROM sponsors WHERE id = ?", (sponsor_id,))
        if not sponsor:
            return jsonify({"success": False, "message": "Sponsor not found."}), 404
        return jsonify({"success": True, "sponsor": sponsor})

    if request.method == "DELETE":
        db.execute("DELETE FROM sponsors WHERE id = ?", (sponsor_id,))
        return jsonify({"success": True, "message": "Sponsor deleted successfully."})

    data = request.get_json(force=True)
    errors = validate_sponsor(data)
    if errors:
        return jsonify({"success": False, "message": " ".join(errors)}), 400

    prev = db.query_one("SELECT status FROM sponsors WHERE id = ?", (sponsor_id,))
    db.execute(
        """UPDATE sponsors SET company_name=?, industry=?, website=?, location=?, target_audience=?, keywords=?,
           sponsorship_category=?, budget_potential=?, estimated_budget=?, contact_person=?, contact_email=?,
           contact_phone=?, status=?, notes=? WHERE id=?""",
        (data["company_name"], data.get("industry", ""), data.get("website", ""), data.get("location", ""),
         data.get("target_audience", ""), data.get("keywords", ""), data.get("sponsorship_category", ""),
         data.get("budget_potential", "Medium"), int(data.get("estimated_budget") or 0),
         data.get("contact_person", ""), data.get("contact_email", ""), data.get("contact_phone", ""),
         data.get("status", "Discovered"), data.get("notes", ""), sponsor_id),
    )
    if prev and data.get("status") and prev["status"] != data["status"]:
        spx.log_interaction(sponsor_id, "Note", "System", "Status updated",
                             f"Sponsor status changed from '{prev['status']}' to '{data['status']}'.")
    spx.evaluate_and_save_score(sponsor_id)
    return jsonify({"success": True, "message": "Sponsor updated successfully."})


@app.route("/sponsors/<int:sponsor_id>")
@login_required()
def sponsor_profile(sponsor_id):
    sponsor = db.query_one("SELECT * FROM sponsors WHERE id = ?", (sponsor_id,))
    if not sponsor:
        flash("Sponsor not found.", "error")
        return redirect(url_for("sponsors_page"))
    timeline = spx.get_sponsor_timeline(sponsor_id)
    followups = db.query_all(
        "SELECT * FROM sponsor_followups WHERE sponsor_id = ? ORDER BY due_date ASC", (sponsor_id,)
    )
    opportunities = db.query_all(
        "SELECT * FROM sponsorship_opportunities WHERE sponsor_id = ? ORDER BY created_at DESC", (sponsor_id,)
    )
    return render_template(
        "sponsor_profile.html", sponsor=sponsor, timeline=timeline,
        followups=followups, opportunities=opportunities,
    )


@app.route("/api/sponsors/<int:sponsor_id>/generate-message", methods=["POST"])
@login_required()
def api_generate_message(sponsor_id):
    sponsor = db.query_one("SELECT * FROM sponsors WHERE id = ?", (sponsor_id,))
    if not sponsor:
        return jsonify({"success": False, "message": "Sponsor not found."}), 404
    data = request.get_json(force=True) or {}
    message = spx.generate_outreach_message(
        sponsor, contact_person=data.get("contact_person"), package=data.get("package"),
        amount=data.get("amount") or None, benefits=data.get("benefits"),
    )
    return jsonify({"success": True, "message_text": message})


@app.route("/api/sponsors/<int:sponsor_id>/interactions", methods=["GET", "POST"])
@login_required()
def api_sponsor_interactions(sponsor_id):
    if request.method == "GET":
        return jsonify(spx.get_sponsor_timeline(sponsor_id))

    data = request.get_json(force=True)
    if not data.get("interaction_type"):
        return jsonify({"success": False, "message": "Interaction type is required."}), 400

    spx.log_interaction(
        sponsor_id, data["interaction_type"], data.get("communication_method", "Other"),
        data.get("subject", ""), data.get("message", ""), data.get("sponsor_response"),
        data.get("next_action"), data.get("follow_up_date"),
        created_by=session.get("admin_name", "Event Organizer"),
    )

    new_status = data.get("new_status")
    if new_status:
        db.execute("UPDATE sponsors SET status = ? WHERE id = ?", (new_status, sponsor_id))

    if data.get("follow_up_date"):
        spx.schedule_followup(sponsor_id, data["follow_up_date"],
                               data.get("next_action") or "Follow up on recent communication.")

    return jsonify({"success": True, "message": "Communication recorded successfully."})


@app.route("/api/sponsors/<int:sponsor_id>/followups", methods=["POST"])
@login_required()
def api_schedule_followup(sponsor_id):
    data = request.get_json(force=True)
    if not data.get("due_date"):
        return jsonify({"success": False, "message": "A follow-up date is required."}), 400
    spx.schedule_followup(sponsor_id, data["due_date"], data.get("reason", ""))
    return jsonify({"success": True, "message": "Follow-up scheduled."})


@app.route("/api/followups/<int:followup_id>/complete", methods=["POST"])
@login_required()
def api_complete_followup(followup_id):
    spx.complete_followup(followup_id)
    return jsonify({"success": True, "message": "Follow-up marked as completed."})


@app.route("/api/sponsors/<int:sponsor_id>/opportunity", methods=["POST"])
@login_required()
def api_sponsor_opportunity(sponsor_id):
    data = request.get_json(force=True)
    opp_id = db.execute(
        """INSERT INTO sponsorship_opportunities
           (sponsor_id, package, benefits, amount_requested, amount_committed, amount_received, status, confirmed_date)
           VALUES (?,?,?,?,?,?,?,?)""",
        (sponsor_id, data.get("package", ""), data.get("benefits", ""),
         float(data.get("amount_requested") or 0), float(data.get("amount_committed") or 0),
         float(data.get("amount_received") or 0), data.get("status", "Proposed"),
         data.get("confirmed_date")),
    )
    if data.get("status") == "Confirmed":
        db.execute("UPDATE sponsors SET status = 'Confirmed' WHERE id = ?", (sponsor_id,))
        spx.log_interaction(sponsor_id, "Confirmation", data.get("communication_method", "Email"),
                             "Sponsorship Confirmed",
                             f"Sponsor confirmed as {data.get('package','sponsor')} "
                             f"with committed amount ₹{float(data.get('amount_committed') or 0):,.0f}.")
    elif data.get("status") == "Rejected":
        db.execute("UPDATE sponsors SET status = 'Rejected' WHERE id = ?", (sponsor_id,))
        spx.log_interaction(sponsor_id, "Rejection", data.get("communication_method", "Email"),
                             "Sponsorship Declined", "Sponsor declined the sponsorship opportunity.")
    return jsonify({"success": True, "message": "Sponsorship opportunity recorded.", "id": opp_id})


# -----------------------------------------------------------------
# Sponsor Outreach Management (standalone Approach Sponsor workflow)
# -----------------------------------------------------------------
@app.route("/sponsor-outreach")
@login_required()
def sponsor_outreach():
    sponsors = db.query_all(
        "SELECT * FROM sponsors WHERE status NOT IN ('Rejected','Inactive') ORDER BY suitability_score DESC"
    )
    preselect_id = request.args.get("sponsor_id", type=int)
    return render_template("sponsor_outreach.html", sponsors=sponsors, preselect_id=preselect_id)


# -----------------------------------------------------------------
# Follow-Up Management
# -----------------------------------------------------------------
@app.route("/sponsor-followups")
@login_required()
def sponsor_followups_page():
    refresh_all_alerts()
    buckets = spx.get_followup_buckets()
    return render_template("sponsor_followups.html", buckets=buckets)


# -----------------------------------------------------------------
# Sponsor Performance Tracking
# -----------------------------------------------------------------
@app.route("/sponsor-performance")
@login_required()
def sponsor_performance():
    perf = spx.get_performance_stats()
    return render_template("sponsor_performance.html", perf=perf)


@app.route("/api/charts/sponsorship")
@login_required()
def api_charts_sponsorship():
    return jsonify(spx.get_performance_stats()["charts"])


# -----------------------------------------------------------------
# Incident Agent
# -----------------------------------------------------------------
@app.route("/incident-agent", methods=["GET", "POST"])
@login_required()
def incident_agent():
    recommendation = None
    requirements = {}
    if request.method == "POST":
        requirements = {
            "category": request.form.get("category", ""),
            "priority": request.form.get("priority", ""),
            "description": request.form.get("description", ""),
        }
        recommendation = inc.recommend_action(
            requirements["category"], requirements["priority"], requirements["description"]
        )
    return render_template("incident_agent.html", recommendation=recommendation, requirements=requirements)


# -----------------------------------------------------------------
# Incident Management
# -----------------------------------------------------------------
@app.route("/incidents")
@login_required()
def incidents_page():
    filters = {
        "q": request.args.get("q", ""), "category": request.args.get("category", ""),
        "priority": request.args.get("priority", ""), "status": request.args.get("status", ""),
    }
    incidents_list = inc.search_incidents(filters)
    stats = inc.get_dashboard_stats()
    return render_template("incidents.html", incidents=incidents_list, filters=filters, stats=stats)


@app.route("/incidents/new", methods=["GET", "POST"])
@login_required()
def report_incident():
    if request.method == "POST":
        category = request.form.get("category", "")
        priority = request.form.get("priority") or inc.suggest_priority(category)
        description = request.form.get("description", "")
        recommendation = inc.recommend_action(category, priority, description)

        data = {
            "title": request.form.get("title", "").strip(),
            "description": description,
            "category": category,
            "priority": priority,
            "related_venue_id": request.form.get("related_venue_id") or None,
            "related_session_id": request.form.get("related_session_id") or None,
            "related_speaker_id": request.form.get("related_speaker_id") or None,
            "related_sponsor_id": request.form.get("related_sponsor_id") or None,
            "assigned_to": request.form.get("assigned_to", "").strip() or None,
            "due_date": request.form.get("due_date") or None,
            "reported_by": session.get("admin_name", "Event Organizer"),
            "recommendation": recommendation,
        }
        if not data["title"]:
            flash("Incident title is required.", "error")
            return redirect(url_for("report_incident"))

        incident_id = inc.create_incident(data)
        inc.refresh_incident_alerts()
        flash("Incident reported successfully. The Incident Agent has generated a recommendation.", "success")
        return redirect(url_for("incident_detail", incident_id=incident_id))

    venues = db.query_all("SELECT * FROM venues ORDER BY name ASC")
    sessions = db.query_all("SELECT * FROM sessions ORDER BY session_date DESC")
    speakers = db.query_all("SELECT * FROM speakers ORDER BY name ASC")
    sponsors = db.query_all("SELECT * FROM sponsors ORDER BY company_name ASC")
    prefill = {"category": request.args.get("category", ""), "priority": request.args.get("priority", "")}
    return render_template("report_incident.html", venues=venues, sessions=sessions,
                            speakers=speakers, sponsors=sponsors, prefill=prefill)


@app.route("/incidents/<int:incident_id>")
@login_required()
def incident_detail(incident_id):
    incident = db.query_one(
        """SELECT i.*, v.name as venue_name, sp.name as speaker_name, sn.company_name as sponsor_name
           FROM incidents i
           LEFT JOIN venues v ON i.related_venue_id = v.id
           LEFT JOIN speakers sp ON i.related_speaker_id = sp.id
           LEFT JOIN sponsors sn ON i.related_sponsor_id = sn.id
           WHERE i.id = ?""", (incident_id,)
    )
    if not incident:
        flash("Incident not found.", "error")
        return redirect(url_for("incidents_page"))
    timeline = inc.get_incident_timeline(incident_id)
    return render_template("incident_detail.html", incident=incident, timeline=timeline)


@app.route("/api/incidents/<int:incident_id>/update", methods=["POST"])
@login_required()
def api_update_incident(incident_id):
    data = request.get_json(force=True)
    update_text = (data.get("update_text") or "").strip()
    status_change = data.get("status_change") or None
    if not update_text and not status_change:
        return jsonify({"success": False, "message": "Provide an update note or a status change."}), 400

    inc.log_update(incident_id, update_text or f"Status changed to {status_change}.",
                    status_change, session.get("admin_name", "Event Organizer"))

    if data.get("assigned_to"):
        db.execute("UPDATE incidents SET assigned_to = ? WHERE id = ?", (data["assigned_to"], incident_id))
        if status_change is None:
            inc.log_update(incident_id, f"Assigned to {data['assigned_to']}.", "Assigned",
                            session.get("admin_name", "Event Organizer"))

    if data.get("resolution"):
        db.execute("UPDATE incidents SET resolution = ? WHERE id = ?", (data["resolution"], incident_id))

    return jsonify({"success": True, "message": "Incident updated successfully."})


@app.route("/api/incidents/<int:incident_id>", methods=["DELETE"])
@login_required()
def api_delete_incident(incident_id):
    db.execute("DELETE FROM incidents WHERE id = ?", (incident_id,))
    return jsonify({"success": True, "message": "Incident removed successfully."})


@app.route("/api/charts/incidents")
@login_required()
def api_charts_incidents():
    return jsonify(inc.get_dashboard_stats()["charts"])


# -----------------------------------------------------------------
# Operational Alerts
# -----------------------------------------------------------------
@app.route("/alerts")
@login_required()
def alerts_page():
    refresh_all_alerts()
    module_filter = request.args.get("module", "")
    severity_filter = request.args.get("severity", "")
    alert_list = alerts.get_alerts(module=module_filter or None, severity=severity_filter or None)
    counts = alerts.get_alert_counts()
    return render_template("alerts.html", alerts=alert_list, counts=counts,
                            module_filter=module_filter, severity_filter=severity_filter)


@app.route("/api/alerts/<int:alert_id>/read", methods=["POST"])
@login_required()
def api_alert_read(alert_id):
    alerts.mark_read(alert_id)
    return jsonify({"success": True})


@app.route("/api/alerts/<int:alert_id>/dismiss", methods=["POST"])
@login_required()
def api_alert_dismiss(alert_id):
    alerts.dismiss_alert(alert_id)
    return jsonify({"success": True, "message": "Alert dismissed."})


@app.route("/api/alerts/mark-all-read", methods=["POST"])
@login_required()
def api_alerts_mark_all_read():
    alerts.mark_all_read()
    return jsonify({"success": True, "message": "All alerts marked as read."})


# =================================================================
# MILESTONE 4 — EVENT INTELLIGENCE ENGINE
# =================================================================
@app.route("/event-intelligence")
@login_required()
def event_intelligence_page():
    refresh_all_alerts()
    snapshot = ei.analyze_event()
    trend = ei.get_health_trend()
    return render_template("event_intelligence.html", snapshot=snapshot, trend=trend)


@app.route("/api/intelligence/summary")
@login_required()
def api_intelligence_summary():
    return jsonify({"success": True, "data": ei.analyze_event()})


@app.route("/api/intelligence/health")
@login_required()
def api_intelligence_health():
    snapshot = ei.analyze_event()
    return jsonify({"success": True, "data": {
        "health_score": snapshot["health_score"], "health_label": snapshot["health_label"],
        "readiness_score": snapshot["readiness_score"], "components": snapshot["components"],
        "trend": ei.get_health_trend(),
    }})


@app.route("/api/intelligence/risks")
@login_required()
def api_intelligence_risks():
    return jsonify({"success": True, "data": risk_engine_mod.get_all_risks()})


@app.route("/api/intelligence/recommendations")
@login_required()
def api_intelligence_recommendations():
    snapshot = ei.analyze_event()
    return jsonify({"success": True, "data": snapshot["recommendations"]})


@app.route("/api/intelligence/attendance")
@login_required()
def api_intelligence_attendance():
    users = db.query_all("SELECT * FROM users")
    if not users:
        return jsonify({"success": True, "data": {"message": "No data available yet"}})
    return jsonify({"success": True, "data": {
        "prediction": ai_model.predict_attendance_percentage(users),
        "trend": ai_model.get_registration_trend(users, days=7),
        "no_shows": ai_model.predict_no_shows(users)[:20],
    }})


@app.route("/api/intelligence/sponsorship")
@login_required()
def api_intelligence_sponsorship():
    return jsonify({"success": True, "data": spx.get_performance_stats()})


@app.route("/api/intelligence/incidents")
@login_required()
def api_intelligence_incidents():
    return jsonify({"success": True, "data": inc.get_dashboard_stats()})


# =================================================================
# MILESTONE 4 — EXECUTIVE DASHBOARD
# =================================================================
@app.route("/executive-dashboard")
@login_required()
def executive_dashboard():
    refresh_all_alerts()
    snapshot = ei.analyze_event()
    trend = ei.get_health_trend()
    register = risk_engine_mod.get_all_risks()
    sessions = db.query_all(
        """SELECT s.*, v.name as venue_name, sp.name as speaker_name FROM sessions s
           LEFT JOIN venues v ON s.venue_id = v.id LEFT JOIN speakers sp ON s.speaker_id = sp.id
           WHERE s.status != 'Cancelled' ORDER BY s.session_date ASC, s.start_time ASC LIMIT 6"""
    )
    followups = spx.get_followup_buckets()
    critical_incidents = db.query_all(
        "SELECT * FROM incidents WHERE priority = 'Critical' AND status NOT IN ('Resolved','Verified','Closed') ORDER BY created_at DESC LIMIT 5"
    )
    active_alerts = alerts.get_alerts(unresolved_only=True)[:6]
    return render_template(
        "executive_dashboard.html",
        snapshot=snapshot, trend=trend, register=register,
        upcoming_sessions=sessions,
        pending_followups=(followups["overdue"] + followups["due_today"])[:6],
        critical_incidents=critical_incidents,
        active_alerts=active_alerts,
    )


# =================================================================
# MILESTONE 4 — AGENT ORCHESTRATION
# =================================================================
@app.route("/agent-orchestration")
@login_required()
def agent_orchestration_page():
    history = orch.get_execution_history(limit=40)
    decisions = orch.get_decision_history(limit=15)
    return render_template("agent_orchestration.html", history=history, decisions=decisions,
                            agent_keys=orch.ALL_AGENT_KEYS)


@app.route("/api/orchestrator/run", methods=["POST"])
@login_required()
def api_orchestrator_run():
    payload = request.get_json(silent=True) or request.form
    problem_text = (payload.get("problem") or "").strip()
    quick_action = (payload.get("quick_action") or "").strip() or None
    if not problem_text and not quick_action:
        return json_error("Provide a 'problem' description or a 'quick_action' key.")
    try:
        result = orch.run_orchestration(
            problem_text=problem_text or None, quick_action=quick_action,
            user=session.get("admin_name", "System"),
        )
        return jsonify({"success": True, "data": result})
    except Exception as e:
        return json_error(f"Orchestration failed: {e}", 500)


@app.route("/api/orchestrator/history")
@login_required()
def api_orchestrator_history():
    return jsonify({"success": True, "data": orch.get_execution_history(limit=50)})


@app.route("/api/orchestrator/status")
@login_required()
def api_orchestrator_status():
    return jsonify({"success": True, "data": {
        "agents_available": orch.ALL_AGENT_KEYS,
        "recent_executions": orch.get_execution_history(limit=5),
    }})


# =================================================================
# MILESTONE 4 — DECISION SUPPORT CENTER
# =================================================================
@app.route("/decision-support")
@login_required()
def decision_support_page():
    return render_template("decision_support.html", sample_questions=dsupport.SAMPLE_QUESTIONS,
                            quick_actions=orch.QUICK_ACTIONS)


@app.route("/api/decision-support/analyze", methods=["POST"])
@login_required()
def api_decision_support_analyze():
    payload = request.get_json(silent=True) or request.form
    question = (payload.get("question") or "").strip()
    if not question:
        return json_error("A 'question' field is required.")
    try:
        result = dsupport.analyze(question, user=session.get("admin_name", "Event Organizer"))
        return jsonify({"success": True, "data": result})
    except Exception as e:
        return json_error(f"Decision support analysis failed: {e}", 500)


@app.route("/api/decision-support", methods=["GET"])
@login_required()
def api_decision_support_get():
    """Convenience GET endpoint (per spec) mirroring the POST analyze route via ?question=."""
    question = (request.args.get("question") or "").strip()
    if not question:
        return json_error("A 'question' query parameter is required.")
    result = dsupport.analyze(question, user=session.get("admin_name", "Event Organizer"))
    return jsonify({"success": True, "data": result})


# =================================================================
# MILESTONE 4 — RISK CENTER
# =================================================================
@app.route("/risk-center")
@login_required()
def risk_center_page():
    register = risk_engine_mod.get_all_risks()
    return render_template("risk_center.html", register=register)


# =================================================================
# MILESTONE 4 — SYSTEM HEALTH
# =================================================================
@app.route("/system-health")
@login_required()
def system_health_page():
    health = _compute_system_health()
    return render_template("system_health.html", health=health)


@app.route("/api/system-health")
def api_system_health():
    # Deliberately unauthenticated (like a standard health-check endpoint)
    # but only exposes non-sensitive operational status.
    return jsonify({"success": True, "data": _compute_system_health()})


def _compute_system_health():
    start = time.time()
    db_status = "Connected"
    try:
        db.query_one("SELECT 1 as ok")
    except Exception:
        db_status = "Unavailable"
    response_time_ms = round((time.time() - start) * 1000, 2)

    try:
        alert_total = alerts.get_alert_counts().get("total", 0)
    except Exception:
        alert_total = None

    last_intel = db.query_one("SELECT generated_at FROM event_intelligence ORDER BY id DESC LIMIT 1")

    components = [
        {"name": "Application", "status": "Healthy"},
        {"name": "Database", "status": db_status},
        {"name": "Intelligence Engine", "status": "Running"},
        {"name": "Agent Orchestrator", "status": "Running"},
        {"name": "APIs", "status": "Operational"},
    ]
    for c in components:
        try:
            db.execute(
                "INSERT INTO system_health (component, status, response_time_ms) VALUES (?,?,?)",
                (c["name"], c["status"], response_time_ms),
            )
        except Exception:
            pass

    return {
        "components": components,
        "response_time_ms": response_time_ms,
        "active_alerts": alert_total,
        "last_intelligence_update": last_intel["generated_at"] if last_intel else "No data available yet",
        "environment": app.config.get("ENV_NAME", os.environ.get("APP_ENV", "production")),
        "version": "Milestone 4.0",
        "checked_at": datetime.now().isoformat(timespec="seconds"),
    }


# =================================================================
# MILESTONE 4 — EXECUTIVE REPORT
# =================================================================
@app.route("/executive-report")
@login_required()
def executive_report_page():
    snapshot = ei.analyze_event()
    register = risk_engine_mod.get_all_risks()
    return render_template("executive_report.html", snapshot=snapshot, register=register)


@app.route("/api/executive-report")
@login_required()
def api_executive_report():
    snapshot = ei.analyze_event()
    register = risk_engine_mod.get_all_risks()
    return jsonify({"success": True, "data": {"snapshot": snapshot, "risks": register}})


@app.route("/executive-report/download/pdf")
@login_required()
def executive_report_pdf():
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet
    except ImportError:
        return json_error("PDF generation requires 'reportlab'.", 500)

    snapshot = ei.analyze_event()
    register = risk_engine_mod.get_all_risks()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("RegisterAI — Executive Intelligence Report", styles["Title"]))
    elements.append(Paragraph(f"Generated on {datetime.now().strftime('%d %b %Y, %H:%M')}", styles["Normal"]))
    elements.append(Spacer(1, 14))

    elements.append(Paragraph("<b>Event Health</b>", styles["Heading2"]))
    elements.append(Paragraph(
        f"Health Score: {snapshot['health_score']}/100 ({snapshot['health_label']}) &nbsp;&nbsp; "
        f"Readiness Score: {snapshot['readiness_score']}/100", styles["Normal"]))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("<b>Executive Summary</b>", styles["Heading2"]))
    elements.append(Paragraph(snapshot["executive_summary"], styles["Normal"]))
    elements.append(Spacer(1, 10))

    t = snapshot["totals"]
    elements.append(Paragraph("<b>Key Metrics</b>", styles["Heading2"]))
    metrics_table = Table([
        ["Total Registrations", t["total_registrations"]],
        ["Expected Attendance %", f"{t['expected_attendance_pct']}%"],
        ["Checked-in", f"{t['checked_in']} ({t['checkin_pct']}%)"],
        ["Venue Utilization", f"{t['venue_utilization_pct']}%"],
        ["Speaker Utilization", f"{t['speaker_utilization_pct']}%"],
        ["Sponsorship Confirmed", t["sponsorship_confirmed"]],
        ["Sponsorship Committed", f"Rs. {t['sponsorship_amount_committed']:,.0f}"],
        ["Open Incidents", t["open_incidents"]],
        ["Critical Incidents", t["critical_incidents"]],
        ["Active Alerts", t["active_alerts"]],
    ], colWidths=[220, 220])
    metrics_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F3F1FE")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    elements.append(metrics_table)
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("<b>Key Risks</b>", styles["Heading2"]))
    for r in snapshot["key_risks"]:
        elements.append(Paragraph(f"• {r}", styles["Normal"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("<b>AI Recommendations</b>", styles["Heading2"]))
    for r in snapshot["recommendations"]:
        elements.append(Paragraph(f"[{r['priority']}] ({r['area']}) {r['text']}", styles["Normal"]))
    elements.append(Spacer(1, 12))

    elements.append(Paragraph("<b>Risk Register (Top 10)</b>", styles["Heading2"]))
    risk_table_data = [["Severity", "Module", "Title", "Recommended Action"]]
    for r in register["risks"][:10]:
        risk_table_data.append([r["severity"], r["module"], r["title"], r["recommended_action"]])
    risk_table = Table(risk_table_data, repeatRows=1, colWidths=[55, 65, 170, 190])
    risk_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6C5CE7")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    elements.append(risk_table)

    doc.build(elements)
    buf.seek(0)

    try:
        db.execute("INSERT INTO executive_reports (format, health_score, generated_by) VALUES (?,?,?)",
                    ("PDF", snapshot["health_score"], session.get("admin_name", "system")))
    except Exception:
        pass

    return send_file(buf, mimetype="application/pdf", as_attachment=True,
                      download_name="executive_intelligence_report.pdf")


@app.route("/executive-report/download/csv")
@login_required()
def executive_report_csv():
    snapshot = ei.analyze_event()
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["RegisterAI Executive Intelligence Report"])
    writer.writerow(["Generated At", snapshot["generated_at"]])
    writer.writerow([])
    writer.writerow(["Metric", "Value"])
    for k, v in snapshot["totals"].items():
        writer.writerow([k.replace("_", " ").title(), v])
    writer.writerow([])
    writer.writerow(["Key Risks"])
    for r in snapshot["key_risks"]:
        writer.writerow([r])
    writer.writerow([])
    writer.writerow(["Priority", "Area", "Recommendation"])
    for r in snapshot["recommendations"]:
        writer.writerow([r["priority"], r["area"], r["text"]])

    try:
        db.execute("INSERT INTO executive_reports (format, health_score, generated_by) VALUES (?,?,?)",
                    ("CSV", snapshot["health_score"], session.get("admin_name", "system")))
    except Exception:
        pass

    resp = Response(output.getvalue(), mimetype="text/csv")
    resp.headers["Content-Disposition"] = "attachment; filename=executive_intelligence_report.csv"
    return resp


# =================================================================
# ERROR HANDLERS
# =================================================================
@app.errorhandler(404)
def not_found(e):
    if request.path.startswith("/api/"):
        return json_error("Resource not found.", 404)
    return render_template("404.html"), 404


@app.errorhandler(403)
def forbidden(e):
    if request.path.startswith("/api/"):
        return json_error("You do not have permission to access this resource.", 403)
    return render_template("403.html"), 403


@app.errorhandler(500)
def server_error(e):
    # Never leak stack traces to the user; log server-side only.
    app.logger.exception("Unhandled server error")
    if request.path.startswith("/api/"):
        return json_error("An unexpected server error occurred.", 500)
    return render_template("500.html"), 500


# =================================================================
# ENTRY POINT
# =================================================================
if __name__ == "__main__":
    db.init_db(force=False)
    port = int(os.environ.get("PORT", 5000))
    app.run(debug=app.config.get("DEBUG", False), host="0.0.0.0", port=port)
